spring:
  datasource:
    url: jdbc:mysql://localhost:3306/javaweb
    username: root
    password: 54188
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8181
